fix: implement std::error::Error for data-url
This commit implements std::error::Error for errors in the `data-url`
crate. This commit does not implement `Error` on `DecodeError` because
there is no trait bound for `Error` on the `E` type argument of
`DecodeError`.